name: 2017 in Haskell

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    name: Run Haskell AoC 2017 Solutions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo6 libncurses6

      - name: Install Haskell (GHC & Cabal)
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.2.8'
          cabal-version: '3.10.1.0'

      - name: Install Required Libraries (vector)
        run: |
          cabal update
          cabal install --lib vector
          ghc-pkg recache
          echo "export GHC_PACKAGE_PATH=$(ghc --print-libdir)/package.conf.d" >> $GITHUB_ENV

      - name: Start Timer
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Run AoC 2017 Solutions in Order
        run: |
          cd 2017
          for day in {01..25}; do
            for part in 1 2; do
              file="2017-${day}-${part}.hs"
              if [[ -f "$file" ]]; then
                echo "Running $file..."
                sh run "$file"
              else
                echo "Skipping missing file: $file"
              fi
            done
          done

      - name: End Timer & Format Execution Time
        run: |
          end_time=$(date +%s)
          total_time=$((end_time - start_time))
          minutes=$((total_time / 60))
          seconds=$((total_time % 60))
          formatted_time=$(printf "%d:%02d" "$minutes" "$seconds")
          echo "execution_time=$formatted_time" >> $GITHUB_ENV
          echo "{\"schemaVersion\": 1, \"label\": \"Execution Time\", \"message\": \"$formatted_time\", \"color\": \"blue\"}" > execution_time_2017.json

      - name: Commit Execution Time Badge to GitHub Pages
        run: |
          mkdir -p badges
          mv execution_time_2017.json badges/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add badges/execution_time_2017.json
          git commit -m "Update execution time badge for 2017 [skip ci]" || echo "No changes to commit"
          git pull --no-rebase --strategy=ours origin main && git push
