name: AoC 2016 Solutions Check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    name: Run Rust AoC 2016 Solutions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust (Version 1.70.0)
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.70.0

      - name: Start Timer
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

      - name: Build AoC 2016 Solutions
        run: |
          cd 2016
          cargo build

      - name: Run AoC 2016 Solutions in Order
        run: |
          cd 2016
          for day in {01..25}; do
            for part in 1 2; do
              file="2016-${day}-${part}.rs"
              puzzle_num="2016/${day}/${part}"
              if [[ -f "$file" ]]; then
                echo "Running $puzzle_num..."
                ./target/debug/advent_of_code "$puzzle_num"
              else
                echo "Skipping missing file: $file"
              fi
            done
          done

      - name: End Timer & Format Execution Time
        run: |
          end_time=$(date +%s)
          total_time=$((end_time - start_time))
          minutes=$((total_time / 60))
          seconds=$((total_time % 60))
          formatted_time=$(printf "%d:%02d" "$minutes" "$seconds")
          echo "execution_time=$formatted_time" >> $GITHUB_ENV
          echo "{\"label\": \"Execution Time\", \"status\": \"$formatted_time\", \"color\": \"blue\"}" > execution_time_2016.json

      - name: Commit Execution Time Badge to GitHub Pages
        run: |
          mkdir -p badges
          mv execution_time_2016.json badges/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add badges/execution_time_2016.json
          git commit -m "Update execution time badge for 2016 [skip ci]" || echo "No changes to commit"
          git pull --rebase origin main && git push
